version: "3.8"

services:
  #################################################
  # 1) MySQL service
  #################################################
  bk_hope_mysql:
    image: mysql:8.0
    container_name: bk_hope_mysql
    restart: always
    env_file:
      - .env
    environment:
      # Sử dụng biến từ .env:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:     ${MYSQL_DATABASE}
      MYSQL_USER:         ${MYSQL_USER}
      MYSQL_PASSWORD:     ${MYSQL_PASSWORD}
      
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - bk_hope_mysql_data:/var/lib/mysql
    networks:
      - backend-network 

  #################################################
  # 2) Backend (Python / FastAPI / Uvicorn)
  #################################################
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    restart: unless-stopped
    depends_on:
      - bk_hope_mysql
    env_file:
      - .env
    environment:
      # Xây dựng DATABASE_URL cho SQLAlchemy / ORM:
      DATABASE_URL: "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:3306/${MYSQL_DATABASE}"
    ports:
      - "7070:7070"
    command: ["python", "run.py"]
    networks:
      - backend-network 

volumes:
  bk_hope_mysql_data:
  
networks:
  backend-network:
    driver: bridge